---
functional:
  -
non-functional:
  - Сайт должен быть разработан с учётом удобства использования и оптимизирован для скорости работ
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильных устройствах
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - сайт должен быть способен обрабатывать большое количество траффика (1000 одновременных пользователей)
implict:
