---
functional:
  - Пользователь должен иметь возможность зарегистрироваться в системе
  - Пользователь должен иметь возможность авторизоваться в системе под валидным логином и паролем
  - Пользователь должен иметь возможность создавать игры в системе
  - Пользователь должен иметь возможность играть в активную игру и победить в ней
  - Пользователь должен иметь возможность просматривать активные игры других игроков в системе в режиме реального времени
  - Пользователь должен иметь возможность просматривать запись завершившихся игр в системе
non-functional:
  - Сайт должен быть разработан с учётом удобства использования и оптимизирован для скорости работ
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильных устройствах
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - сайт должен быть способен обрабатывать большое количество траффика (1000 одновременных пользователей)
implict:
  - Пользователь должен иметь возможность зарегистрироваться в системе с помощью своего профиля на GitHub
  - Пользователь должен иметь возможность попробовать игру с ботом без регистрации в системе
  - Пользователь должен иметь возможность ознакомиться с правилами игры в системе
  - Во время активной игры пользователь должен иметь возможность контролировать время, видеть код своего соперника, проверять свой код во время игры.
  - Пользователь должен иметь возможность переподключиться в игру, если произошёл обрыв связи во вермя игры.
  - Пользователь должен иметь возможность отслеживать свой рейтинг в системе.
  - Пользователь должен иметь возможность завершить игру
  - Зритель игры должен иметь возможность отправить сообщение в чат игры.
  - Пользователь должен иметь возможность просматривать историю игр.
  - Пользователь должен имет возможность выбирать язык игры в системе